from django.urls import path
from player.views import (
    JukeOroniView,
    BoxView,
    BoxViewRadio,
    AlbumView,
    vol_down,
    vol_reset,
    vol_up,
    up_31hz,
    reset_31hz,
    down_31hz,
    up_63hz,
    reset_63hz,
    down_63hz,
    up_125hz,
    reset_125hz,
    down_125hz,
    up_250hz,
    reset_250hz,
    down_250hz,
    up_500hz,
    reset_500hz,
    down_500hz,
    up_1khz,
    reset_1khz,
    down_1khz,
    up_2khz,
    reset_2khz,
    down_2khz,
    up_4khz,
    reset_4khz,
    down_4khz,
    up_8khz,
    reset_8khz,
    down_8khz,
    up_16khz,
    reset_16khz,
    down_16khz,
)


urlpatterns = [
    # Jukebox
    path('', JukeOroniView.as_view(), name='jukeoroni_index'),
    path('jukebox/', BoxView.as_view(), name='jukebox'),
    path('radio/', BoxViewRadio.as_view(), name='radio'),
    path('meditationbox/', BoxView.as_view(), name='meditationbox'),
    path('podcastbox/', BoxView.as_view(), name='podcastbox'),
    path('videobox/', BoxView.as_view(), name='videobox'),
    # path('audiobookbox/', JukeOroniView.box_index, name='audiobookbox'),
    path('jukebox/<int:queue_index>/pop/', JukeOroniView.pop_track_from_queue, name='jukebox pop track'),
    path('meditationbox/<int:queue_index>/pop/', JukeOroniView.pop_track_from_queue, name='meditationbox pop track'),
    path('podcastbox/<int:queue_index>/pop/', JukeOroniView.pop_track_from_queue, name='podcastbox pop track'),
    # path('audiobookbox/<int:queue_index>/pop/', JukeOroniView.pop_track_from_queue, name='audiobookbox pop track'),
    path('jukebox/<int:queue_index>/as_first/', JukeOroniView.set_first_in_queue, name='jukebox set first'),
    path('meditationbox/<int:queue_index>/as_first/', JukeOroniView.set_first_in_queue, name='meditationbox set first'),
    path('podcastbox/<int:queue_index>/as_first/', JukeOroniView.set_first_in_queue, name='podcastbox set first'),
    # path('audiobookbox/<int:queue_index>/as_first/', JukeOroniView.set_first_in_queue, name='audiobookbox set first'),
    path('set_jukebox/', JukeOroniView.set_jukebox, name='set mode jukebox'),
    path('set_meditationbox/', JukeOroniView.set_meditationbox, name='set mode meditation'),
    path('set_podcastbox/', JukeOroniView.set_podcastbox, name='set mode podcast'),
    path('set_videobox/', JukeOroniView.set_videobox, name='set mode video'),
    # path('set_audiobookbox/', JukeOroniView.set_audiobookbox, name='set mode audiobookbox'),
    path('set_radio/', JukeOroniView.set_radio, name='set mode radio'),
    path('set_standby/', JukeOroniView.set_standby, name='set mode standby'),
    path('jukebox/play_next/', JukeOroniView.play_next, name='player_play_next'),
    path('meditationbox/play_next/', JukeOroniView.play_next, name='player_play_next'),
    path('podcastbox/play_next/', JukeOroniView.play_next, name='player_play_next'),
    path('videobox/play/', JukeOroniView.play, name='video_play'),
    path('videobox/<str:video_title>/load/', JukeOroniView.load_movie_by_title, name='video_play'),
    # path('videobox/pause/', JukeOroniView.pause, name='video_pause'),
    # path('videobox/resume/', JukeOroniView.resume_video, name='video_resume'),
    # path('audiobookbox/play_next/', JukeOroniView.play_next, name='player_play_next'),
    path('jukebox/update_track_list/', JukeOroniView.update_track_list, name='update_track_list'),
    path('meditationbox/update_track_list/', JukeOroniView.update_track_list, name='update_track_list'),
    path('podcastbox/update_track_list/', JukeOroniView.update_track_list, name='update_track_list'),
    # path('audiobookbox/update_track_list/', JukeOroniView.update_track_list, name='update_track_list'),

    path('jukebox/stop/', JukeOroniView.stop, name='player_stop'),
    path('meditationbox/stop/', JukeOroniView.stop, name='player_stop'),
    path('podcastbox/stop/', JukeOroniView.stop, name='player_stop'),
    path('videobox/stop/', JukeOroniView.stop, name='player_stop'),
    # path('audiobookbox/stop/', JukeOroniView.stop, name='player_stop'),
    path('pause/', JukeOroniView.pause, name='pause'),
    path('resume/', JukeOroniView.resume, name='resume'),
    path('jukebox/switch_mode/', JukeOroniView.switch_mode, name='player_switch_mode'),
    path('meditationbox/switch_mode/', JukeOroniView.switch_mode, name='player_switch_mode'),
    path('podcastbox/switch_mode/', JukeOroniView.switch_mode, name='player_switch_mode'),
    # path('audiobookbox/switch_mode/', JukeOroniView.switch_mode, name='player_switch_mode'),

    path('jukebox/albums/<int:album_id>/', AlbumView.play_album, name='player_play_album'),
    path('meditationbox/albums/<int:album_id>/', AlbumView.play_album, name='player_play_album'),
    # path('podcastbox/albums/<int:album_id>/', JukeOroniView.play_album, name='player_play_album'),
    # path('audiobookbox/albums/<int:album_id>/', JukeOroniView.play_album, name='player_play_album'),
    path('jukebox/albums/search/', AlbumView.as_view(), name='search_albums'),
    path('meditationbox/albums/search/', AlbumView.as_view(), name='search_albums'),
    path('jukebox/albums/', AlbumView.as_view(), name='player_albums'),
    path('meditationbox/albums/', AlbumView.as_view(), name='player_albums'),
    # path('podcastbox/albums/', JukeOroniView.albums, name='player_albums'),
    # path('audiobookbox/albums/', JukeOroniView.albums, name='player_albums'),

    # path('jukebox/tracks/play_track/<int:track_id>/', JukeOroniView.play_track, name='player_play_track'),
    # path('jukebox/tracks/', JukeOroniView.tracks, name='player_tracks'),
    # path('meditationbox/tracks/', JukeOroniView.tracks, name='player_tracks'),

    # Radio
    path('radio/<str:display_name_short>/play/', BoxViewRadio.radio_play, name='radio_play'),
    path('radio/stop/', BoxViewRadio.radio_stop, name='radio_stop'),

    path('vol_down/', vol_down, name='vol_down'),
    path('vol_reset/', vol_reset, name='vol_reset'),
    path('vol_up/', vol_up, name='vol_up'),

    path('up_31hz/', up_31hz, name='up_31hz'),
    path('reset_31hz/', reset_31hz, name='reset_31hz'),
    path('down_31hz/', down_31hz, name='down_31hz'),

    path('up_63hz/', up_63hz, name='up_63hz'),
    path('reset_63hz/', reset_63hz, name='reset_63hz'),
    path('down_63hz/', down_63hz, name='down_63hz'),

    path('up_125hz/', up_125hz, name='up_125hz'),
    path('reset_125hz/', reset_125hz, name='reset_125hz'),
    path('down_125hz/', down_125hz, name='down_125hz'),

    path('up_250hz/', up_250hz, name='up_250hz'),
    path('reset_250hz/', reset_250hz, name='reset_250hz'),
    path('down_250hz/', down_250hz, name='down_250hz'),

    path('up_500hz/', up_500hz, name='up_500hz'),
    path('reset_500hz/', reset_500hz, name='reset_500hz'),
    path('down_500hz/', down_500hz, name='down_500hz'),

    path('up_1khz/', up_1khz, name='up_1khz'),
    path('reset_1khz/', reset_1khz, name='reset_1khz'),
    path('down_1khz/', down_1khz, name='down_1khz'),

    path('up_2khz/', up_2khz, name='up_2khz'),
    path('reset_2khz/', reset_2khz, name='reset_2khz'),
    path('down_2khz/', down_2khz, name='down_2khz'),

    path('up_4khz/', up_4khz, name='up_4khz'),
    path('reset_4khz/', reset_4khz, name='reset_4khz'),
    path('down_4khz/', down_4khz, name='down_4khz'),

    path('up_8khz/', up_8khz, name='up_8khz'),
    path('reset_8khz/', reset_8khz, name='reset_8khz'),
    path('down_8khz/', down_8khz, name='down_8khz'),

    path('up_16khz/', up_16khz, name='up_16khz'),
    path('reset_16khz/', reset_16khz, name='reset_16khz'),
    path('down_16khz/', down_16khz, name='down_16khz'),

    # path('', index_redirect, name='index_redirect'),
]

