# Generated by Django 3.2.5 on 2021-07-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_channel_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='url_logo',
            field=models.URLField(null=True),
        ),
    ]
