# Generated by Django 3.2.5 on 2021-07-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_channel_url_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='url_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
