---
# /usr/bin/ansible-playbook --inventory-file '/home/michael/git/repos/jukeoroni/ansible/hosts' -v '/home/michael/git/repos/jukeoroni/ansible/postgres.yml'

- name: JukeOroni Postgres install
  # https://pimylifeup.com/raspberry-pi-postgresql/
  hosts: jukeoroni
  vars:
  - db_admin: pi
  - db_login_user: postgres
  - db_name: jukeoroni_db
  - db_user: jukeoroni
  - db_password: 1234
  become: yes

  tasks:

  # User postgres gets created automatically upon postgres installation

  - name: Install Packages
    apt:
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
      update_cache: yes
      name:
        - postgresql

  - name: Create admin user with SCRAM-hashed password
    community.postgresql.postgresql_user:
#      name: pi
      name: "{{ db_admin }}"
#      password: "1234"
      password: "{{ db_password }}"
      role_attr_flags: SUPERUSER
    environment:
      PGOPTIONS: "-c password_encryption=scram-sha-256"

# modify /etc/postgresql/11/main/pg_hba.conf
#local all all trust
#host all all 127.0.0.1/32 trust
#host all all ::1/128 trust

# systemctl restart postgresql

  - name: modify trust
    shell: mv /etc/postgresql/11/main/pg_hba.conf /etc/postgresql/11/main/pg_hba.conf.backup

  - name: Creating a file with content
    copy:
      dest: /etc/postgresql/11/main/pg_hba.conf
      content: |
        local all all trust
        host all all 127.0.0.1/32 trust
        host all all ::1/128 trust
      owner: postgres
      group: postgres
      mode: '0640'

  - name: Reload services
    shell: |
      systemctl daemon-reload

  - name: Start Postgres Service
    ansible.builtin.service:
      name: postgresql.service
      state: restarted

  - name: create jukeoroni db
    community.postgresql.postgresql_db:
#      name: jukeoroni_db
      name: "{{ db_name }}"
      encoding: UTF-8
#      login_user: postgres
      login_user: "{{ db_login_user }}"
#      owner: pi
      owner: "{{ db_admin }}"

  - name: Create db user user with SCRAM-hashed password
    community.postgresql.postgresql_user:
#      name: jukeoroni
      name: "{{ db_user }}"
#      password: "1234"
      password: "{{ db_password }}"
    environment:
      PGOPTIONS: "-c password_encryption=scram-sha-256"
